# Generated by Django 5.2.7 on 2025-11-10 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('uf', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Macho'), ('F', 'Femea')], default='M', max_length=1)),
                ('specie', models.CharField(choices=[('D', 'Dog'), ('C', 'Cat'), ('O', 'Other')], default='D', max_length=1)),
                ('status', models.CharField(choices=[('desaparecido', 'Desaparecido'), ('abandonado', 'Abandonado'), ('doação', 'Doação')], default='desaparecido', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('dt_create', models.DateTimeField(auto_now_add=True)),
                ('dt_update', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='animal_location', to='app_animals.location')),
            ],
        ),
        migrations.CreateModel(
            name='PictureGalery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='animal_pictures/')),
                ('dt_insert', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='picture_animal', to='app_animals.animal')),
            ],
        ),
    ]
