# Generated by Django 5.2.7 on 2025-11-02 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenderChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to='animal_pictures/')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='animal_gender', to='app_animals.genderchoices')),
                ('specie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='animal_species', to='app_animals.species')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='animal_status', to='app_animals.status')),
            ],
        ),
    ]
