# Generated by Django 5.2.7 on 2025-11-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_animals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picturegalery',
            name='picture',
            field=models.ImageField(default=1, upload_to='animal_pictures/'),
            preserve_default=False,
        ),
    ]
