# Generated by Django 5.2.7 on 2025-11-11 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_animals', '0002_alter_picturegalery_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picturegalery',
            name='animal',
        ),
    ]
