# Generated by Django 5.2.7 on 2025-11-11 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_animals', '0003_remove_picturegalery_animal'),
    ]

    operations = [
        migrations.AddField(
            model_name='picturegalery',
            name='animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='picture_animal', to='app_animals.animal'),
        ),
    ]
