# Generated by Django 5.2.7 on 2025-11-11 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_animals', '0004_picturegalery_animal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picturegalery',
            name='animal',
        ),
        migrations.AddField(
            model_name='animal',
            name='pictures',
            field=models.ManyToManyField(blank=True, related_name='liked_animals', to='app_animals.picturegalery'),
        ),
    ]
