# Generated by Django 5.2.7 on 2025-11-12 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_animals', '0008_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='age_type',
            field=models.CharField(blank=True, choices=[('mes', 'Mes(es)'), ('ano', 'Ano(s)')], default='mes', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=300),
        ),
    ]
