# Generated by Django 5.2.7 on 2025-12-02 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_animals', '0010_animal_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picturegalery',
            name='animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='picture_animal', to='app_animals.animal'),
        ),
    ]
