# Generated by Django 5.2.7 on 2025-12-03 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_animals', '0011_alter_picturegalery_animal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_animal', to='app_animals.animal'),
        ),
    ]
